### ISSUE TITLE
Error Configured

### ISSUE THREAD

**Issue by recherst** [Andrewmika/Xcode-Server-and-Continuous-Integration-Guide-in-Chinese#1]
![QQ20191018-183750](https://user-images.githubusercontent.com/17176518/67087896-76cdb980-f1d6-11e9-94f0-513a86f02409.png)
请教一下，遇到过这个问题吗？
这个是我的 pre-integration script
![QQ20191018-184004](https://user-images.githubusercontent.com/17176518/67088028-b8f6fb00-f1d6-11e9-83ab-c33e21da6f22.png)

**Comment by Andrewmika** [comment]
你重新配置Configuration试试。另外进入工程目录可以使用cd ${XCS_PRIMARY_REPO_DIR}

**Comment by recherst** [comment]
> 你重新配置Configuration试试。另外进入工程目录可以使用cd ${XCS_PRIMARY_REPO_DIR}

@Andrewmika  方便留个联系方式指导一下吗

**Comment by Andrewmika** [comment]
具体问题你可以在这里进行描述，这边别人遇到问题也可以看到。

**Comment by recherst** [comment]
![QQ20191023-122653](https://user-images.githubusercontent.com/17176518/67357790-fec61180-f590-11e9-9ff8-27e81222a494.png)
![QQ20191023-122708](https://user-images.githubusercontent.com/17176518/67357802-04235c00-f591-11e9-8b68-3884a79f0b52.png)
![QQ20191023-122906](https://user-images.githubusercontent.com/17176518/67357808-0a193d00-f591-11e9-918b-c456373c9100.png)
![QQ20191023-122919](https://user-images.githubusercontent.com/17176518/67357816-0e455a80-f591-11e9-9822-9cfa5b41c1b7.png)
![QQ20191023-122949](https://user-images.githubusercontent.com/17176518/67357829-169d9580-f591-11e9-8705-fc1abe8bc9cc.png)
![QQ20191023-122958](https://user-images.githubusercontent.com/17176518/67357838-1dc4a380-f591-11e9-9b97-bc35ae238244.png)
![QQ20191023-123015](https://user-images.githubusercontent.com/17176518/67357847-23ba8480-f591-11e9-8e8e-c5f2b7e106d5.png)
![QQ20191023-123035](https://user-images.githubusercontent.com/17176518/67357849-27e6a200-f591-11e9-851c-ee1592d3d9b2.png)
网上的教程大体说的都一样，但配置完后就是不能通过集成。
遇到最多的报错是：
`Error Configured scheme xxx could not be found, it may have been renamed or removed after the bot was created.`

**Comment by Andrewmika** [comment]
你不会scheme没有勾选shared吧

**Comment by recherst** [comment]
![QQ20191025-153415](https://user-images.githubusercontent.com/17176518/67552127-fad6f280-f73c-11e9-87f5-5ecabbca3325.png)
勾选了
Xcode 是 11.1

**Comment by Andrewmika** [comment]
加我qq 674681605

**Comment by Andrewmika** [comment]
pod install 问题
